name: moose
channels:
  - https://conda.software.inl.gov/public
  - conda-forge
dependencies:
  - poetry
  - netcdf4
  - scikit-learn
  - scikit-optimize
prefix: /rcp/rcp42/home/shenyaojin/miniforge/envs/moose
